'use strict';
const items=[
{name:'Margherita',category:'Pizza',price:19,cost:4.6,qty:[180,165,157]},
{name:'Margherita Piu',category:'Pizza',price:21,cost:5.7,qty:[125,110,106]},
{name:'Funghi',category:'Pizza',price:20,cost:6.1,qty:[98,93,88]},
{name:'Fichi',category:'Pizza',price:20,cost:5.8,qty:[84,80,77]},
{name:'Penne Verde',category:'Pasta',price:18,cost:3.9,qty:[62,57,53]},
{name:'Veal Bolognese',category:'Pasta',price:24,cost:8.4,qty:[92,86,82]},
{name:'Di Mare',category:'Pasta',price:32,cost:14.2,qty:[38,42,40]},
{name:'Burrata',category:'Appetizers',price:18,cost:6.8,qty:[88,81,75]},
{name:'Suppli Al Telefono',category:'Appetizers',price:14,cost:3.5,qty:[72,65,61]},
{name:'Gelato',category:'Desserts',price:8,cost:1.7,qty:[93,85,80]},
{name:'Crème Brûlée',category:'Desserts',price:12,cost:2.8,qty:[57,51,46]}];
const tasks=[{title:'Try a Penne Verde server mention',text:'For one week, ask servers to mention Penne Verde when guests ask for a pasta recommendation. Keep its price unchanged.',measure:'Review units per 100 orders and total contribution after ingredients.',tag:'Menu · owner + floor team'}, {title:'Verify Di Mare ingredient costs',text:'Check the latest seafood invoice and the actual portion sizes with the kitchen. Update the sample recipe cost in Menu & costs to explore the effect.',measure:'Confirm the cost per plate before considering a price or portion change.',tag:'Costs · owner + kitchen'}, {title:'Review quieter weekday shifts',text:'Compare Tuesday and Wednesday sales with bookings, prep work, and staffing. This demo does not include payroll, so it cannot calculate labor savings.',measure:'Decide whether a small scheduling trial is appropriate; keep service quality in view.',tag:'Operations · owner review'}];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const dollars=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const pizzaIcon=(size=18)=>`<svg class="pizza-icon" width="${size}" height="${size}" viewBox="0 0 32 32" aria-hidden="true" focusable="false"><path d="M6.5 8.5C9.1 6.4 12.5 5.3 16 5.3s6.9 1.1 9.5 3.2L16 27.5 6.5 8.5Z" fill="#fff0ef" stroke="#ce4542" stroke-width="1.8" stroke-linejoin="round"/><path d="M6.5 8.5C9.1 6.4 12.5 5.3 16 5.3s6.9 1.1 9.5 3.2" fill="none" stroke="#ce4542" stroke-width="3" stroke-linecap="round"/><circle cx="13" cy="13" r="1.7" fill="#ce4542"/><circle cx="19.7" cy="11.7" r="1.7" fill="#ce4542"/><circle cx="17" cy="19.8" r="1.7" fill="#ce4542"/></svg>`;
const icon=(name,size=18)=>`<span class="ui-icon" aria-hidden="true" style="--icon:url('icons/${name}.svg');width:${size}px;height:${size}px"></span>`;
const foodIcon=x=>x.category==='Pizza'?pizzaIcon(18):icon(x.category==='Pasta'?'utensils':x.category==='Appetizers'?'salad':x.name==='Gelato'?'ice-cream-bowl':'cake-slice');
document.querySelectorAll('nav button>span').forEach((e,i)=>{e.innerHTML=icon(['chart-no-axes-combined','utensils','sparkles'][i]);});
document.querySelectorAll('.notes article>span').forEach((e,i)=>{e.innerHTML=icon(['utensils','chef-hat','calendar-days'][i],22);});
document.querySelector('.section-icon').innerHTML=icon('chart-no-axes-combined');
document.querySelector('.section-icon').removeAttribute('data-pizza-icon');
document.querySelector('.focus-pizza').innerHTML=icon('utensils',100);
document.querySelector('.focus-pizza').removeAttribute('data-pizza-icon');
document.querySelectorAll('[data-pizza-icon]').forEach(e=>{e.innerHTML=pizzaIcon(e.dataset.pizzaIcon==='hero'?122:18)});
let period=0,view='overview',editing=0,done=[],costs={};
try{const stored=JSON.parse(localStorage.getItem('ema-demo-v1')||'{}');done=Array.isArray(stored.done)?stored.done.filter(x=>Number.isInteger(x)&&x>=0&&x<tasks.length):[];for(const [k,v] of Object.entries(stored.costs||{}))if(Number.isFinite(v)&&v>=0&&v<=200)costs[k]=v;}catch{}
const cost=i=>costs[i]??items[i].cost;
const total=p=>items.reduce((s,x)=>s+x.qty[p]*x.price,0);
const count=p=>items.reduce((s,x)=>s+x.qty[p],0);
const contribution=p=>items.reduce((s,x,i)=>s+x.qty[p]*(x.price-cost(i)),0);
let plans={};
try{plans=JSON.parse(localStorage.getItem('ema-plans-v2')||'{}')||{};}catch{}
function plan(){const p=plans[period]||{};return {accepted:Array.isArray(p.accepted)?p.accepted.filter(i=>Number.isInteger(i)&&i>=0&&i<tasks.length):[],dismissed:Array.isArray(p.dismissed)?p.dismissed.filter(i=>Number.isInteger(i)&&i>=0&&i<tasks.length):[],done:Array.isArray(p.done)?p.done:[]};}
function persist(){try{localStorage.setItem('ema-demo-v1',JSON.stringify({costs,done}));localStorage.setItem('ema-plans-v2',JSON.stringify(plans));}catch{}}
function notice(s){const e=document.getElementById('toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300);}
function change(a,b){const d=(a-b)/b*100;return `<span class="${d>=0?'up':'down'}">${d>=0?'+':''}${d.toFixed(1)}%</span>`;}
function render(){
const sales=total(period),previous=total(period+1),contr=contribution(period),pct=contr/sales*100;
document.getElementById('metrics').innerHTML=[['Food sales',money(sales),change(sales,previous)+'vs. prior week'],['Dishes sold',count(period).toLocaleString(),change(count(period),count(period+1))+'vs. prior week'],['After ingredient costs',money(contr),change(contr,contribution(period+1))+'vs. prior week'],['Food margin',pct.toFixed(1)+'%','Before labor, rent & other costs']].map((x,i)=>`<article class="metric"><div class="metric-label">${icon(['dollar-sign','utensils','receipt','chart-no-axes-combined'][i])}${x[0]}</div><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');
const weights=period===0?[.11,.12,.15,.2,.24,.18]:[.1,.12,.16,.19,.25,.18];const split=(n,w)=>{let a=w.map(v=>Math.floor(v*n));a[a.length-1]+=n-a.reduce((s,v)=>s+v,0);return a};const days=split(sales,weights),prior=split(previous,[.1,.12,.16,.19,.25,.18]);const max=Math.max(...days,...prior)*1.15;
document.getElementById('sales-chart').innerHTML=days.map((v,i)=>`<div class="day"><div class="bars"><div class="bar previous" style="height:${prior[i]/max*100}%" title="Prior week: ${money(prior[i])}"></div><div class="bar" style="height:${v/max*100}%" title="Selected week: ${money(v)}"><b>${money(v)}</b></div></div><span class="day-label">${['Tue','Wed','Thu','Fri','Sat','Sun'][i]}</span></div>`).join('');
document.getElementById('sales-chart').setAttribute('aria-label','Daily sample sales. '+days.map((v,i)=>['Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][i]+': '+money(v)+', prior week '+money(prior[i])).join('; '));
document.getElementById('chart-period').textContent=period===0?'September 1–6, 2026 · compared with August 25–30':'August 25–30, 2026 · compared with August 18–23';
document.getElementById('strongest').textContent='Saturday led the week · '+money(days[4]);
document.getElementById('focus-copy').textContent=`${items[4].qty[period]} plates sold in this sample week. Check its contribution against your other dishes, then test a server recommendation.`;
document.getElementById('penne-margin').textContent=dollars(18-cost(4));
const ranked=items.map((x,i)=>({...x,i,contrib:x.qty[period]*(x.price-cost(i))})).sort((a,b)=>b.contrib-a.contrib);
document.getElementById('top-items').innerHTML=ranked.slice(0,5).map((x,i)=>`<div class="top-row"><span class="rank">0${i+1}</span><div class="dish"><span class="dish-name">${foodIcon(x)}<span>${x.name}</span></span><small>${x.category} · ${x.qty[period]} sold</small></div><div class="top-value">${money(x.contrib)}<small>${dollars(x.price-cost(x.i))} / plate</small></div></div>`).join('');
const category=document.getElementById('category').value;
document.getElementById('menu-rows').innerHTML=ranked.filter(x=>category==='All categories'||x.category===category).map(x=>`<tr><td><span class="menu-dish">${foodIcon(x)}<span>${x.name}<small>${x.category}</small></span></span></td><td>${x.qty[period]}</td><td>${dollars(x.price)}</td><td>${dollars(cost(x.i))}</td><td>${dollars(x.price-cost(x.i))}</td><td>${money(x.contrib)}</td><td><button data-edit="${x.i}" aria-label="Edit ingredient cost for ${x.name}">Edit cost</button></td></tr>`).join('');
const p=plan(),pending=tasks.map((_,i)=>i).filter(i=>!p.accepted.includes(i)&&!p.dismissed.includes(i));
const findings=[`Penne Verde sold ${items[4].qty[period]} plates, leaving ${dollars(18-cost(4))} per plate after estimated ingredient costs. This is not net profit.`,`Di Mare's estimated ingredients cost ${dollars(cost(6))} of its $32 price (${(cost(6)/32*100).toFixed(1)}%). This alone does not mean the recipe needs changing.`,`Tuesday and Wednesday had ${money(days[0])} and ${money(days[1])} in sample food sales, the two lowest days this week. Staffing data is not included.`];
document.querySelector('#actions-view .panel-title h2').innerHTML=icon('sparkles',20)+'System suggestions';
document.querySelector('#actions-view .panel-title p').textContent='Suggested by the system from this week’s sample sales and ingredient costs. Choose which to try.';
const shortTitles=['Give Penne Verde a mention','Check Di Mare’s recipe cost','Review quieter weekdays'];
const shortAdvice=['Try recommending it when guests ask for pasta.','Check seafood prices and portions before changing anything.','Compare staffing and bookings for Tuesday and Wednesday.'];
const stats=[[[dollars(18-cost(4)),'per plate after ingredients'],[items[4].qty[period],'plates sold']],[[dollars(cost(6)),'ingredients per plate'],[(cost(6)/32*100).toFixed(1)+'%','of the $32 menu price']],[[money(days[0]),'Tuesday sales'],[money(days[1]),'Wednesday sales']]];
document.getElementById('actions-list').innerHTML=`<div class="suggestion-stack">${pending.map(i=>`<article class="suggestion-card"><span class="suggestion-category">${icon(['utensils','chef-hat','calendar-days'][i],18)}${['MENU','RECIPE COSTS','WEEKDAY SALES'][i]}</span><h3>${shortTitles[i]}</h3><span class="system-suggestion">${icon('sparkles',14)}System suggestion</span><div class="suggestion-stats">${stats[i].map(([value,label])=>`<div><strong>${value}</strong><span>${label}</span></div>`).join('')}</div><p>${shortAdvice[i]}</p><div class="suggestion-buttons"><button data-decision="accept" data-id="${i}">Add to plan</button><button data-decision="dismiss" data-id="${i}">Dismiss</button></div></article>`).join('')||'<p class="plan-empty">All suggestions reviewed for this week.</p>'}${p.dismissed.length?'<button class="text-button restore-suggestions" data-decision="restore">Restore dismissed suggestions</button>':''}<p class="suggestion-note">Demo recommendations using fictional data, not a live analysis. Amounts after ingredients are not net profit. Staffing data is not included.</p></div><section class="weekly-plan-panel" aria-labelledby="weekly-plan-title"><div class="panel-title"><div><h2 id="weekly-plan-title">${icon('clipboard-check',20)}Your weekly plan</h2><p>${p.accepted.filter(i=>p.done.includes(i)).length} of ${p.accepted.length} complete · Approved by you</p></div></div>${p.accepted.length?p.accepted.map(i=>`<article class="action ${p.done.includes(i)?'done':''}"><input type="checkbox" id="task-${i}" data-task="${i}" ${p.done.includes(i)?'checked':''}><div><h3><label for="task-${i}">${shortTitles[i]}</label></h3><p>${shortAdvice[i]}</p><details><summary>How to follow up</summary><p>${tasks[i].measure}</p></details><button class="text-button" data-decision="remove" data-id="${i}">Remove</button></div></article>`).join(''):'<div class="plan-empty"><strong>Nothing planned yet.</strong><p>Add a suggestion when you’re ready to try it.</p></div>'}<p class="plan-storage">Saved on this device for the selected week.</p></section>`;
document.getElementById('progress-label').textContent=`${pending.length} to review · ${p.accepted.filter(i=>p.done.includes(i)).length} of ${p.accepted.length} planned actions complete`;document.getElementById('action-count').textContent=pending.length;
}
function setView(v){view=v;for(const x of ['overview','menu','actions'])document.getElementById(x+'-view').hidden=x!==v;document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.view===v);if(b.dataset.view===v)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});document.getElementById('page-title').textContent={overview:'Your week, at a glance.',menu:'Know what each dish brings in.',actions:'This week’s suggested actions.'}[v];document.getElementById('page-description').textContent={overview:'See what sold, what changed, and where to focus next.',menu:'Popularity is one part of the picture. Ingredient costs are another.',actions:'The system suggests where to focus. You decide what belongs in your plan.'}[v];}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
document.getElementById('period').addEventListener('change',e=>{period=Number(e.target.value);render()});
document.getElementById('category').addEventListener('change',render);
document.getElementById('all-menu').addEventListener('click',()=>setView('menu'));
document.getElementById('review-action').addEventListener('click',()=>setView('actions'));
document.getElementById('menu-rows').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(!b)return;editing=Number(b.dataset.edit);document.getElementById('cost-title').textContent=items[editing].name;document.getElementById('cost-input').value=cost(editing).toFixed(2);document.getElementById('cost-dialog').showModal()});
document.getElementById('close-dialog').addEventListener('click',()=>document.getElementById('cost-dialog').close());
document.getElementById('cost-form').addEventListener('submit',e=>{e.preventDefault();const v=Number(document.getElementById('cost-input').value);if(!Number.isFinite(v)||v<0||v>200)return;costs[editing]=v;persist();render();document.getElementById('cost-dialog').close();notice('Sample cost updated across both weeks.');});
document.getElementById('actions-list').addEventListener('click',e=>{const b=e.target.closest('[data-decision]');if(!b)return;const p=plan(),i=Number(b.dataset.id),a=b.dataset.decision;if(a==='restore')p.dismissed=[];else if(a==='accept'){p.accepted=[...new Set([...p.accepted,i])];p.dismissed=p.dismissed.filter(x=>x!==i);}else if(a==='dismiss')p.dismissed=[...new Set([...p.dismissed,i])];else if(a==='remove'){p.accepted=p.accepted.filter(x=>x!==i);p.done=p.done.filter(x=>x!==i);}plans[period]=p;persist();render();notice(a==='accept'?'Added to your weekly plan.':a==='dismiss'?'Suggestion dismissed.':a==='restore'?'Dismissed suggestions restored.':'Returned to suggestions.');});
document.getElementById('actions-list').addEventListener('change',e=>{if(!e.target.matches('[data-task]'))return;const p=plan(),i=Number(e.target.dataset.task);if(!p.accepted.includes(i))return;p.done=e.target.checked?[...new Set([...p.done,i])]:p.done.filter(x=>x!==i);plans[period]=p;persist();render()});
document.getElementById('reset').addEventListener('click',()=>{costs={};done=[];plans={};period=0;document.getElementById('period').value='0';document.getElementById('category').value='All categories';persist();render();setView('overview');notice('Demo reset to original sample data.');});
render();setView('overview');
